mendoc/business

dump/ecole241business.sql

Creation et envoie du Dump de la BDD

ajout du dump

---

application/models/Gestionnaire.php

Creation du model Gestionnaire avce les fonctions : lister et ajouter

creation du model du gestionnaire

---

application/models/Paiement.php

J'ai ajoute le modèle paiement avec une méthode pour vérifier si un apprenant a paye, si il est apprenant !
Utile pour le listing des candidats

Ajout du Modele Paiement

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/candidats.php

Listing des candidats accessibles depuis la méthode 'candidats'

Ajout du listing des candidats

---

application/controllers/Gestionnaire.php
application/models/Candidat_model.php
application/models/Paiement_model.php
application/views/back/gestionnaire/candidats.php
application/views/back/gestionnaire/details_candidat.php

J'ai ajoute la méthode qui donne les informations d'un candidat 
**Hotfix**: Il manque la vue

Ajout de la vue détail du candidat

---

dump/ecole241business.sql

nouveau dump

---

application/controllers/Commercial.php
application/controllers/Gestionnaire.php
application/models/Commercial_model.php
application/models/Gestionnaire_model.php
application/views/back/commercial/statistiques.php
application/views/back/gestionnaire/statistiques.php

Le Gestionnaire peut gerer les retraits

Fonctionnalité Gestionnaire pour retrait

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/transactions_commercial.php
application/views/zones/top.php

J'ai modifie le header transactions , c'est maintenant un dropdown qui montre les transactions cote candidats et cote commercial

Listing des transactions

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/ressources.php

Il est maintenant possible de supprimer une ressource depuis la liste

Possibilite de supprimer ressource

---

application/models/Statistique_model.php

j'ai corrigé une fonction pour avoir un retour

Statistique model

---

application/views/back/commercial/statistiques.php

Responsive du formulaire de demande de retrait

Correctif commercial

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/details_candidat.php

J'ai ajoute les champs pour le moyen de paiement et le justificatif

Ajustement de paiement candidat

---

application/controllers/Commercial.php
application/models/Commercial_model.php
application/views/back/commercial/mot_de_passe_oublie.php
application/views/front/commercial/connexion.php

On peut désormais réinitialiser son mot de passe :yum:

Reinitialiser mot de passe

---

application/controllers/Gestionnaire.php

A l'ajout d'un gestionnaire , le mot de passe est maintenant hashe !!

Hashing des mots de passe inscription

---

application/views/back/gestionnaire/details_commercial.php
theme/assets/css/dashboard.css

 vue details d'un commerciale

---

application/controllers/Gestionnaire.php

2 route ont été ajoute pour hasher les mots de passe en base de donnes .
- Une pour les gestionnaires **hashing_gest**
- Une pour les commerciaux **hashing_com**

Hashing base de donnees

---

application/controllers/Gestionnaire.php
application/models/Statistique_model.php
application/views/back/gestionnaire/statistiques.php

Il est maintenant possible de consulter depuis le dashboard gestionnaire le nombre total de visite , le listing du trafic ( nom du commercial - nombre de visite ) et des performances (nom du commercial - nombre de candidat)

Ajout des stats gestionnaire

---

application/views/back/gestionnaire/candidats.php

affichage du nombre total de candidat dans la vue - listing des candidats

affichage du nombre total de candidat

---

application/views/front/landing/accueil.php
application/views/front/landing/commercial.php

J'ai ajoute le code hotjar dans la landing Page (Accueil )

Ajout du code Hotjar  dans l'accueil

---

application/views/back/commercial/mot_de_passe_oublie.php
application/views/back/gestionnaire/connexion.php
application/views/back/gestionnaire/mot_passe_oublie.php
application/views/front/candidat/inscription.php
application/views/front/candidat/message_inscription.php
application/views/front/commercial/connexion.php
application/views/front/commercial/inscription.php
application/views/zones/head.php

J'ai ajoute le script Hotjar sur tout le reste des heads !!

Ajout des scripts Hotjar sur tout heads

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/connexion.php

J'ai utilise des sessions qui expire dans 1 mois si l'utilisateur accepte que l'on se souvienne de lui.
Dans le cas d'un gestionnaire

Amelioration des sessions

---

application/controllers/Gestionnaire.php
application/models/Statistique_model.php
application/views/back/gestionnaire/statistiques.php

On peut desormais consulter sur le dashboard gestionnaire, le nombre d'inscrit par jour !! :yum:

Ajout stat : nb inscrit par jour

---

application/config/autoload.php
application/controllers/Candidat.php
application/views/front/candidat/inscription_candidat.php

Validation des champs du nouveau formulaire enregistrement candidat et affichage des erreurs.

Validation des champs du nouveau formulaire enregistrement candidat et affichage des erreurs.

---

application/views/back/gestionnaire/statistiques.php
application/views/zones/top.php

Responsive du dashboad Gestionnaire 
- menu responsive
- Tableaux responsive

Vue gestionnaire

---

application/views/front/candidat/inscription-candidat.php
application/views/front/candidat/inscription_candidat.php

Je l'ai ajoute dans inscription candidat

Ajout du script Hotjar inscription can

---

application/controllers/Leaderboard.php
application/views/front/leaderboard/classement.php

Modification des fichiers leaderboard.php & classement.php

Ajout du taux de conversion

---

.htaccess
application/config/config.php
application/views/front/leaderboard/classement.php

Retrait de l'index.php dans config
Correction de l'erreur Taux de conversion généré par la visite

Correction de la division par 0

---

application/views/back/gestionnaire/candidats.php

Dans la vue listing des candidats , il est désormais possible de connaitre leur statut ( en ligne ou en présentiel )

Affichage du type de cours dans candidats

---

application/config/autoload.php
application/controllers/Commercial.php
application/models/Commercial_model.php
application/views/front/commercial/inscription-commercial.php

validation des champs du formulaire inscription commerciale.
affichage des erreurs sur le formulaire .

Controller commercial validation

---

application/views/front/leaderboard/classement.php

Modification du Ternaire

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/candidats.php

Le prix s'affiche correctement dans le listing des candidats !!

Affichage correct des prix du candidat

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/details_candidat.php

Désormais , il y a une vérification au niveau du paiement du candidat. 
On empêche tout paiement si le montant estime pour un candidat a déjà été atteint .

Correctif du paiement candidat

---

application/views/back/commercial/statistiques.php

J'ai retire les regex pour la validation du numero

Correctif demande de retrait

---

application/views/front/commercial/inscription-commercial.php
theme/assets/css/inscription-commercial.css

ajout de nouveau format jour/mois/année, ainsi que la suppression des champs obligatoires prénom et numéro whatsapp

Nouvelle branch

---

application/controllers/Candidat.php

Désactivation temporaire de la validation de l'adresse e-mail pour le formulaire d'enregistrement du candidat

Désactivation validation de l'adresse e-mail

---

application/controllers/Candidat.php

J'ai supprime la validation des numéros de téléphones ( whatsapp également)

Suppression de la validation des numeros

---

application/controllers/Candidat.php

Annulation des validation des numéros de téléphone et WhatsApp sur le formulaire d'enregistrement du candidat.

Déploiement de la version 1.01.01

---

application/views/zones/head.php

Hotjar ne va plus scanner les pages du dashboard

Suppression du script Hotjar dans head.php

---

application/controllers/Candidat.php
application/views/front/candidat/inscription_candidat.php

Ajout des validations sur les champs de sélection.
Teste des erreurs, teste sur l'enregistrement d'un candidat .
Ajout de l'affichage d'erreur sur le formulaire pour les champs de sélection jours mois et année .

amélioration des validation du formulaire candidat

---

application/models/Retrait_model.php

Toutes les demandes de retrait d'un commercial

Ajout du listing des demandes de retrait

---

application/controllers/Commercial.php
application/views/front/commercial/inscription-commercial.php

gestion de l'inscription du commercial.
gestion des erreurs.

validation du formulaire enregistrement commercial

---

application/views/front/landing/accueil.php

ajustement du menu berger à partir de 6OOpx

correction du menu berger

---

application/views/front/landing/accueil.php
application/views/front/landing/commercial.php

ajustement du menu berger à partir de 6OOpx

correction Berger commercial

---

application/controllers/Commercial.php
application/views/back/commercial/statistiques.php

Ajout d'une condition au niveau de la demande de retrait .
Impossible de retirer si le montant demande est supérieur au solde . :yum:

Correctif commercial retrait paiement

---

application/views/front/landing/accueil.php

On a remonte les coûts de la formation

Correctif Landing page

---

application/views/front/landing/accueil.php

Le lien du logo de la landing page accueil **redirige proprement** ( Pointe vers notre page d'accueil ) :yum:

Correctif  du lien du logo

---

application/controllers/Commercial.php
application/views/email/commercial/inscription.php

gestion de l'envoi du mail pour inscription commerciale

gestion de l'email de confirmation du commercial

---

application/views/email/candidat/payement.php

Message envoyé au candidat lors de l'enregistrement d'un payement.

Confirmation du paiement d'un candidat

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/commerciaux.php
application/views/back/gestionnaire/details_commercial.php

Il est désormais possible de consulter le détail d'un commercial depuis le listing (gestionnaire)

Ajout du detail commercial

---

application/views/front/commercial/inscription_commercial.php
theme/assets/css/inscription-commercial.css

Amelioration du Responsive inscription commercial et de notre politique ...

Amelioration formulaire inscription commercial

---

application/views/front/candidat/inscription_candidat.php

correction s' enregistrer prix  margin top

correction du formulaire prix et texte

---

application/views/front/leaderboard/classement.php

Les résultats du leaderboard sont réactualises toutes les 1 minute!!

Reactualisation du leaderboard toute 1 min

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/nouvelle_ressource.php

Les bugs ont été corrige et ils est désormais possible de créer les ressources

Correctif creation de ressources

---

application/controllers/Gestionnaire.php
application/views/email/gestionnaire/inscription.php

Changement de l'email d'inscription du gestionnaire

Email inscription gestionnaire

---

application/controllers/Commercial.php
application/views/back/commercial/ressources.php

gestion des téléchargements des ressources .

gestion des ressources

---

application/views/front/landing/accueil.php

ajout du pixel facebook sur la page d'accueil lainding page

ajout de pixel Facebook sur accueil

---

application/views/front/candidat/inscription_candidat.php

ajout du pixel facebook sur la page inscription candidat

ajout de pixel Facebook sur vue inscription candidat

---

application/views/front/candidat/inscription.php
application/views/front/candidat/inscription_candidat.php
application/views/front/candidat/message_inscription.php
application/views/front/landing/accueil.php

Correctif des scripts facebook pixel et Hotjar

Deploiement 1.0.8

---

application/views/front/candidat/inscription.php
application/views/front/candidat/inscription_candidat.php
application/views/front/candidat/message_inscription.php
application/views/front/landing/accueil.php

Déploiement 1.0.9 

---

application/views/front/candidat/inscription_candidat.php
application/views/front/candidat/message_inscription.php
application/views/front/landing/accueil.php

Déploiement 1.0.10  

---

application/controllers/Gestionnaire.php

- J'ai ajoute les headers dans l'envoie de l'email de l'inscription du gestionnaire 
- Correctif de la variable mot de passe

Correctif de l'email inscription gestionnaire

---

application/views/zones/head.php

retirer le script du google analytics du head de tous les dachboards

retrait du Google Analytics des dashboard

---

application/views/email/commercial/inscription.php

Je viens de retirer l' addresse e-mail supplémentairee sure-maill inscription commercial et gestionnaire pour commercial.

retrait de l'adresse email et gestionnaire dans les textes

---

application/views/back/commercial/mot_de_passe_oublie.php
application/views/back/gestionnaire/connexion.php
application/views/back/gestionnaire/mot_passe_oublie.php
application/views/front/candidat/inscription_candidat.php
application/views/front/candidat/message_inscription.php
application/views/front/commercial/connexion.php
application/views/front/commercial/inscription_commercial.php
application/views/front/landing/accueil.php
application/views/front/landing/commercial.php

ajustement des titres des vues

ajustement des titres des pages

---

application/controllers/Gestionnaire.php

Jusqu’à maintenant , la suppression d'un ressource se faisait uniquement dans la base de données .
Maintenant ,l'action supprime aussi le fichier au niveau du serveur .

Correctif : suppression de la ressource

---

application/views/email/gestionnaire/mdp_oubli.php

email recut par le gestionnaire  reinitialisation mot de passe

création de la vue mot de passe oublié pour le gestionnaire

---

application/controllers/Gestionnaire.php
application/views/email/candidat/payement.php

- Correction des fautes d'orthographe dans l'email de paiement du candidat
- Chargement de l'email prévu dans le Gestionnaire

Correctif de l'email de paiement candidat

---

application/controllers/Gestionnaire.php
application/models/Gestionnaire_model.php
application/views/back/gestionnaire/connexion.php
application/views/back/gestionnaire/mot_passe_oublie.php

Le gestionnaire peut maintenant réinitialiser son mot de passe

Fonctionnalité : mot de passe oublie gestionnaire

---

application/views/front/candidat/new_inscriptiom_candidat.php
theme/assets/css/new_form_candidat.css

gestion du responsive uniquement sur mobile sans les tablettes

premiere version du nouveau formulaire

---

application/controllers/Test.php
application/views/front/candidat/new_inscriptiom_candidat.php
application/views/front/leaderboard/classement.php
theme/assets/css/new_form_candidat.css

- Ajout du nouveau formulaire pour le candidat
- Suppression du script hotdjar dans le leaderboard

Correctif mohammed

---

application/views/email/candidat/enregistrement.php
application/views/front/landing/accueil.php

dans la phrase payable en trois tranches

retrait des champs non obligatoire dans email 

---

application/views/front/landing/accueil.php

dans la phrase payable en trois tranches

ajout de trois en chiffre

---

application/controllers/Gestionnaire.php
application/models/Candidat_model.php
application/models/Commercial_model.php
application/views/back/gestionnaire/candidats.php
application/views/back/gestionnaire/details_candidat.php
application/views/back/gestionnaire/modifier_candidat.php
application/views/back/gestionnaire/recherche_resultat.php
application/views/front/candidat/nouveau_formulaire_candidat.php
application/views/zones/top.php
theme/assets/css/dashboard.css
theme/assets/css/new_form_candidat.css

- Ajout de la barre de recherche dans le dashboard gestionnaire
- Ajout de la pagination dans le listing des candidats gestionnaire
- Modification des informations du candidats depuis le detail 
- Amélioration du nouveau formulaire candidat (responsive )
- Desormais il est possible de voir si un candidat est en ligne ou en présentiel depuis les details
- Detail d'un candidat disponible depuis son nom

Ajouts de nouvelles fonctionnalités 

---

application/views/front/landing/accueil.php
application/views/zones/footer.php
application/views/zones/top.php
theme/assets/css/dashboard.css

ajout de l'ancre sur la landing page candidat

Ancres landings

---

application/controllers/Candidat.php
application/views/front/candidat/inscription_candidat.php

modification des affichages des erreurs dans la vue
contrôle du champ nom

gestion du champ nom dans le formulaire candidat

---

application/views/front/landing/commercial.php
application/views/zones/footer.php
application/views/zones/top.php
theme/assets/css/dashboard.css

ajout de l'ancre sur la landing page commercial

Landing commercial

---

application/views/zones/footer.php
application/views/zones/top.php
theme/assets/css/dashboard.css

retrait du bouton déconnexion du footer, ainsi que le bouton copier mon lien du menu burger

Retraits bouton

---

application/controllers/Candidat.php
application/views/front/candidat/inscription_candidat.php

modification des champs à envoyés pour l'email de l'inscription candidat.

Controller candidat email new

---

application/views/front/leaderboard/classement.php

Ajout de la vue du leaderboard

Ajout de la vue

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/commerciaux.php
application/views/front/leaderboard/classement.php

- Correctif commercial , affilies

Déploiement 1.3.2

---

application/config/pagination.php
application/controllers/Gestionnaire.php
application/models/Commercial_model.php
application/models/Gestionnaire_model.php
application/models/Paiement_model.php
application/models/Retrait_model.php
application/views/back/gestionnaire/candidats.php
application/views/back/gestionnaire/commerciaux.php
application/views/back/gestionnaire/gestionnaires.php
application/views/back/gestionnaire/transactions.php
application/views/back/gestionnaire/transactions_commercial.php

- Ajout de la pagination dans les listing du gestionnaire

Pagination dans les listing du gestionnaire

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/candidats.php
application/views/back/gestionnaire/details_candidat.php
application/views/back/gestionnaire/modifier_candidat.php
application/views/back/gestionnaire/recherche_resultat.php

- Amélioration de la vue détail d'un candidat  
- Amélioration du formulaire de modification d'un candidat
- Correctif du listing candidat dans la vue resultat recherche (un candidat ayant tout paye se distingue avec un montant vert )

Amelioration du detail et modification candidat

---

application/controllers/Gestionnaire.php
application/models/Candidat_model.php
application/models/Commercial_model.php
application/views/back/gestionnaire/candidats.php
application/views/back/gestionnaire/commerciaux.php
application/views/back/gestionnaire/transactions.php
application/views/back/gestionnaire/transactions_commercial.php

- On peut exporter en csv les listing du dashboard gestionnaire

Listing gestionnaire csv

---

application/controllers/Candidat.php
application/views/front/candidat/nouveau_formulaire_candidat.php

gestion des erreurs sur la vue formulaire b.
contrôle sur la  validation des champs.

gestion du ab testing

---

application/models/Gestionnaire_model.php

- Correctif de la fonction **récupérer_un_gestionnaire** a la ligne 36

Correctif Gestionnaire model

---

application/controllers/Gestionnaire.php

Passage de 15 a 10 commerciaux pour le listing des performances et du trafic des commerciaux dans le dashboard gestionnaire

correctif stats du gestionnaire

---

application/views/zones/top.php

- Responsive du bouton deconnexion

Déploiement 1.4.1 

---

application/views/front/landing/commercial.php

Correctif de la navbar du commercial dans la Landing Page

Correctif Landing Commercial

---

application/views/zones/top.php

- Correctif de la navbar sur mobile de landing Page commercial

Déploiement 1.4.2 

---

application/views/front/candidat/nouveau_formulaire_candidat.php
theme/assets/css/new_form_candidat.css

mettre les "s" dans les tranches, ainsi que l'ajout des liens cliquables avec l'e-mail et le numéro de tel. Aussi l'ajout du favicon

corrections des fautes dans le formulaire de candidat

---

application/controllers/Gestionnaire.php
application/models/Statistique_model.php
application/views/back/gestionnaire/statistiques.php
application/views/zones/head.php
theme/assets/plugins/charts-c3/plugin.js

Un histogramme sur le dashboard gestionnaire présentant dans les 15 derniers jours les candidats inscrits

Ajout de l'histogramme sur le dashboard

---

application/controllers/Commercial.php

Gestion de email du commercial mot de passe oublié.
Modification de la méthode traitement mot de passe du controller commercial.

Gestion du email mot de passe oublié

---

application/controllers/Commercial.php
application/controllers/Gestionnaire.php
application/views/back/gestionnaire/details_commercial.php
application/views/back/gestionnaire/statistiques.php

- Un compteur pour voir le cumul du reste à payer total pour apprenants 
- Un compteur pour voir la Dette à payer aux commerciaux 
- Un compteur pour le solde restant après la dette à payer pour les commerciaux

Ajout des stats sur le dashboard

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/statistiques.php

- Amelioration du responsive 
- Correctif de l'affichage du cumul du reste a payer des candidats

Correctif des stats

---

application/views/front/candidat/messageinscription.php
theme/assets/css/messageinscription.css

ajout également des liens cliquables dans le pied de page

ajout du pied de page, amélioration de la vue dans l'ensemble

---

application/controllers/Gestionnaire.php

- Correctif du cumul du reste a payer des candidats

correctif stats gestionnaire

---

application/controllers/Candidat.php

Modification de la vue inscription réussi candidat.

Modification de la vue inscription réussi candidat

---

theme/assets/css/messageinscription.css

- Mise a jour de la vue **inscription réussi**

Déploiement 1.5.3

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/details_commercial.php
application/views/back/gestionnaire/statistiques.php

- Ajout d'un camembert dans le dashboard gestionnaire pour l’aperçu du paiement 
- Correctif des fautes sur détail commercial

Ajout du camembert dans le dashboard gestionnaire

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/commerciaux.php
application/views/back/gestionnaire/statistiques.php

- Le montant à payer à un commercial a été ajoute dans le listing des commerciaux
- Correctif de l'affichage des stats sur le dashboard gestionnaire

Ajout du montant a payer commercial

---

application/controllers/Candidat.php
application/views/front/candidat/nouveau_formulaire_candidat.php

Gestion du champ modalité.
Gestion de l'obligation sur le champ modalité de paiement.
Gestion du controller sur la valeur par défaut si le champ est vide.

gestion du champ modalité

---

application/controllers/Commercial.php
application/views/front/candidat/messageinscription.php

Gestion du bonus du commercial.

modification du bonus sur le commercial

---

application/controllers/Gestionnaire.php
application/libraries/Breadcrumb.php
application/views/back/gestionnaire/candidats.php
application/views/back/gestionnaire/commerciaux.php
application/views/back/gestionnaire/details_candidat.php
application/views/back/gestionnaire/details_commercial.php
application/views/back/gestionnaire/modifier_candidat.php
application/views/back/gestionnaire/recherche_resultat.php

- Ajout des breadcrumps dans les listings du gestionnaire (Histoire de naviguer facilement )
- Correctif des fautes dans resultat recherche

Ajout du breadcrumb dans le dashboard gestionnaire

---

application/controllers/Gestionnaire.php

- Listing des commerciaux par ordre du plus grand solde

Listing des commerciaux par le solde

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/details_candidat.php

Amélioration des validations lors de la soumission du montant d'un candidat.
- Désormais , le montant soumis ne peut être supérieur au montant a fournir

correctif du paiement d'un candidat

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/details_candidat.php

- Correctif au niveau du paiement du candidat

Déploiement 1.7.1

---

application/controllers/Commercial.php
application/models/Statistique_model.php
application/views/back/commercial/statistiques.php

Depuis le tableau de bord du commercial , il est désormais possible de voir le nombre d'aspirant

Ajout du nombre d'aspirant - commercial

---

application/config/pagination.php
application/controllers/Commercial.php
application/models/Candidat_model.php
application/views/back/commercial/candidats.php
application/views/zones/top.php

Ajout d'une vue pour dans le dashboard commercial pour ses prospects

Ajout dela vue prospects - dashboard commercial

---

application/controllers/Candidat.php
application/views/front/candidat/inscription_candidat.php
application/views/front/candidat/nouveau_formulaire_candidat.php

- Suppression du montant au type de cours dans formulaire
- Ajout de l'option **Soir** dans l'horaire de formation du formulaire
- Suppression du champ **modalité de paiement** dans le nouveau formulaire

Correctif formulaire candidat 

---

application/views/back/gestionnaire/modifier_candidat.php

Au niveau du gestionnaire , dans la modification des informations d'un candidat : il est désormais possible de choisir **Soir** dans les horaires de formation

prise en compte du soir - modification candidat

---

application/controllers/Candidat.php
application/models/Commercial_model.php

gestion du champ date pour le controller candidat.

géstion du champ date

---

application/controllers/Gestionnaire.php
application/controllers/Leaderboard.php
application/models/Commercial_model.php
application/views/back/commercial/transactions.php
application/views/back/gestionnaire/statistiques.php
application/views/front/leaderboard/classement.php

- Calculer le potentiel chez les aspirants des commerciaux

Ajout de la prévision des commission/ gestionnaire

---

application/controllers/Commercial.php
application/views/back/commercial/candidats.php
application/views/back/commercial/statistiques.php

gestion prospect et aspirant

---

application/controllers/Leaderboard.php
application/views/front/landing/accueil.php

- Correctif de la landing page

Déploiement 1.9.2

---

application/views/back/commercial/candidats.php

Ajout du lien whatsapp pour les prospects commercial

gestion du lien numèro tel pour le candidat du commercial

---

application/controllers/Commercial.php
application/views/email/commercial/retrait_confirme.php

Gestion du mail après retrait du commercial.
Ajout des paramètres dans la vue.

mail confirmation retrait

---

application/views/back/gestionnaire/gestionnaires.php
application/views/errors/html/error_general.php

- Un gestionnaire ne peut donner des droits d’accès ADMIN ( correctif sur la vue )

Droit accès

---

application/views/back/gestionnaire/gestionnaires.php
application/views/errors/html/error_general.php

- Affichage du type des profils dans le listing gestionnaire

Déploiement 1.10.2

---

application/views/back/commercial/candidats.php

ajout des icônes pour les champs numéro des prospects.

gestion icon

---

application/controllers/Gestionnaire.php
application/models/Tresorerie_model.php
application/views/back/gestionnaire/statistiques.php
application/views/back/gestionnaire/transactions_sorties.php
application/views/zones/top.php

- Il est désormais possible pour un trésorier de faire des sorties de caisse

Ajout des sorties de caisse

---

application/controllers/Gestionnaire.php
application/views/back/gestionnaire/details_candidat.php
application/views/back/gestionnaire/statistiques.php
application/views/back/gestionnaire/transactions_commercial.php
application/views/back/gestionnaire/transactions_sorties.php

- Correctif pour le retrait d'un trésorier
- Ajout du total paye aux commerciaux
- Total parti des caisses

correctif retrait trésorier

---

application/controllers/Commercial.php
application/views/back/commercial/statistiques.php

listing des retraits et validité.

gestion des validations d'un retrait - Commercial

---

application/views/back/gestionnaire/details_candidat.php
application/views/back/gestionnaire/transactions.php
application/views/back/gestionnaire/transactions_commercial.php
application/views/back/gestionnaire/transactions_sorties.php

- Ajout de la date d'enregistrement dans les détails d'un candidat
- Correctifs des fautes

Correctif détail candidat

---

application/controllers/Candidat.php
application/views/front/candidat/formulaire_inscription_c.php

gestion du formulaire c du candidat.
modification du label horaire.

modification du formc

---

application/controllers/Gestionnaire.php

- Correctif de l'affichage des dates en français

Déploiement 1.12.1

---

application/controllers/Commercial.php
application/views/back/commercial/statistiques.php

gestion du bouton annulé retrait.
Ajout d'un message pour confirmation d’annulation.

gestion du bouton annulé retrait

---

application/controllers/Commercial.php
application/views/back/commercial/statistiques.php
application/views/back/gestionnaire/details_candidat.php

- gestion du bouton annulé retrait.
- Ajout d'un message pour confirmation d’annulation.

Deploiement 1.13.0

---

application/controllers/Leaderboard.php
application/models/Commercial_model.php
application/views/front/leaderboard/classement.php
theme/assets/css/leaderboard.css

- Ajout du nombre de commerciaux
- Amélioration de la requête du leaderboard

Amélioration du LeaderBoard 

---

application/controllers/Gestionnaire.php
application/models/Commercial_model.php
application/views/back/gestionnaire/commerciaux.php

L'algorithme tri comme celui du leaderboard ( par le nombre d'affilie, puis le nombre d'aspirant, etc..)

Amélioration listing commercial
